### ISSUE TITLE
Uncaught TypeError: plugin.exec is not a function

### ISSUE THREAD

**Issue by 23d1** [swup/scripts-plugin#1]
Getting `Uncaught TypeError: plugin.exec is not a function` error.

```
Uncaught TypeError: plugin.exec is not a function
    at Swup.module.exports [as usePlugin] (app.a6a4d504.js:2065)
    at app.a6a4d504.js:2373
    at Array.forEach (<anonymous>)
    at Swup.enable (app.a6a4d504.js:2372)
    at new Swup (app.a6a4d504.js:2301)
    at Object.parcelRequire.src/app.js.lazysizes (app.a6a4d504.js:18781)
    at newRequire (app.a6a4d504.js:47)
    at app.a6a4d504.js:81
    at app.a6a4d504.js:120
```

**Comment by gmrchk** [comment]
Hi, update swup.

**Comment by 23d1** [comment]
Concise, I love it! :) Running the latest swup and plugin with the same issues, though. Parcel is the bundler I use, if that makes any difference.

**Comment by gmrchk** [comment]
Hm, there is no `exec` method in new plugins, nor `usePlugin` method in swup v2, so I don't think this is an issue with swup. 

Maybe uninstalling swup and installing it again? Or flushing npm cache? It could be possible something is not building properly and the old version of the build script is displayed in the browser as well.

**Comment by 23d1** [comment]
Thanks, will try it out when I get a moment and report back in case someone else runs into the issue.
