### ISSUE TITLE
Scripts are run multiple times when navigating to previous page

### ISSUE THREAD

**Issue by JakobG-dev** [swup/scripts-plugin#7]
When I click the back button of the browser to navigate to the previous page, the scripts are run 3 times. When I go back again the scripts run 6 times. This only happens when I am navigating. When i click a link to change page it works perfectly fine.

Edit:
I just fixed it with following code:
```
let swup = window['currentSwup'];

if (typeof swup === 'object') {
    console.log('#### do noting');
} else {
    swup = new Swup(options);
    window['currentSwup'] = swup;
}
```

**Comment by Geddo** [comment]
+1

**Comment by gmrchk** [comment]
Hi, sorry for the delay. As you've figured out, this likely happens because we're letting the plugin create multiple instances of swup, which should never happen. However, swup cannot control this on its own and your solution is a nice way to go. :thumbsup:
